### ISSUE TITLE
Ajax with sync

### ISSUE THREAD

**Issue by RobinClowers** [chrismccord/sync#121]
We are trying to add sync to an existing rails app that does a lot of ajax requests that render rails partials. When we tried to add sync to one of those partials, we noticed that jquery strips out the sync script tags, which seems to break sync. Is there a workaround for this? If not, would it be possible to patch sync so it could use html comments or some other tag instead of the script tags?

**Comment by mledom** [comment]
@ajb was there any thoughts into using comments instead of script tags? We are using pjax to load our main contents areas and jquery is stripping out the script tags. Sync is working on initial page load but once someone clicks a link to load the page via pjax Sync does not work anymore.

**Comment by ajb** [comment]
No, I only closed the thread due to age/inactivity. I'd be open to a PR or more discussion around this, but at first glance, I'm a little concerned about the performance implications of this, from XRay: https://github.com/brentd/xray-rails/blob/master/app/assets/javascripts/xray.js.coffee#L44-L45

**Comment by mledom** [comment]
Yeah, I was able to get it to work with using comments. Trying to see if there is a better way to handle getting the comments on load instead during each partial.

**Comment by mledom** [comment]
After playing with the comment implementation for a bit I decided to go a different route and wanted to see what you thought. Since each sync partial must start with a containing element, I inserted data-sync-item-id="<authToken" before the end of the first element end bracket (>). Then in the coffee script I say:

if !@$el or @$el.length == 0
      @$el = $("[data-sync-item-id='#{@authToken}']")

Its working well so far but I wanted to see what you thought @ajb.

**Comment by ajb** [comment]
I can't tell you off-hand, since I'm not the author of the original code.
I'm more than happy to review a PR though.

On Mon, Apr 13, 2015 at 2:49 PM, Matt Ledom <notifications@github.com>
wrote:

> After playing with the comment implementation for a bit I decided to go a
> different route and wanted to see what you thought. Since each sync partial
> must start with a containing element, I inserted data-sync-item-id="). Then
> in the coffee script I say:
>
> if !@$el or @$el.length == 0
> @$el = $("[data-sync-item-id='#{@authToken <https://github.com/authToken>
> }']")
>
> Its working well so far but I wanted to see what you thought @ajb
> <https://github.com/ajb>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrismccord/sync/issues/121#issuecomment-92458110>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
What also comes to mind is how would we implement this for sync_new?

On Mon, Apr 13, 2015 at 2:49 PM, Matt Ledom <notifications@github.com>
wrote:

> After playing with the comment implementation for a bit I decided to go a
> different route and wanted to see what you thought. Since each sync partial
> must start with a containing element, I inserted data-sync-item-id="). Then
> in the coffee script I say:
>
> if !@$el or @$el.length == 0
> @$el = $("[data-sync-item-id='#{@authToken <https://github.com/authToken>
> }']")
>
> Its working well so far but I wanted to see what you thought @ajb
> <https://github.com/ajb>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrismccord/sync/issues/121#issuecomment-92458110>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
FWIW, I recently implemented a feature in an app where a partial that contains a sync'd element is rendered via AJAX:

![img](http://take.ms/r8w1O)

I remembered this issue while I was implementing the feature, but it didn't give me any trouble. @RobinClowers, if you've still got time for this ticket, I'm curious to know if I'm misunderstanding your original request, or if there's something else going on here?
