### ISSUE TITLE
Sync don´t refresh partials

### ISSUE THREAD

**Issue by paulocsb** [chrismccord/sync#136]
Hi, i did download the "sync_example". The application it works, but don´t refreshes  the partials after execute the actions. Somebody have an idea?

Thanks.

**Comment by grepruby** [comment]
@paulocsb , can you please tell me what adjustments you did. I think I stuck in same issue. 
My item is updated and that view is called when item is updated, but page is not update.

**Comment by paulocsb** [comment]
@grepruby The faye server was not working properly, so, I set up a server faye isolated to communicate with my application, following the footsteps http://faye.jcoglan.com/ruby.html
