### ISSUE TITLE
Struggling To Sync Outside of Controller

### ISSUE THREAD

**Issue by aberrios85** [chrismccord/sync#137]
Hi I have a sidekiq worker performing:

https://gist.github.com/aberrios85/f7f84ec1580a3d514eed

But it is not syncing correctly in the view. Sync is working fine through the controller.

Controller: https://gist.github.com/aberrios85/f2646a9f7f10ab25c379

Model: https://gist.github.com/aberrios85/a3998d3d2adc09616fdb

The worker completes successfully but no update happens in the view. I'm a bit stumped.

**Comment by shilpi230** [comment]
Hey @flynfish i am also using sidekiq and sync can you please help me out with this issue what configuration of pusher i need to change ?

**Comment by shilpi230** [comment]
hey @chrismccord do you know what configuration changes we need to make to make it work?
