### ISSUE TITLE
Add Pusher encrypted option?

### ISSUE THREAD

**Issue by flynfish** [chrismccord/sync#142]
Seems like a simple addition to add an encryption option for Pusher.

`var pusher = new Pusher('app_key', { encrypted: true } );`

What do you think? I can work on a PR if needed.

**Comment by aeberlin** [comment]
On DOM ready, simply execute this bit of javascript:

```javascript
Sync.adapter.client.encrypted = true;
```

Works fine in development without SSL turned on for the RAILS application.
