### ISSUE TITLE
can't get sync_scopes to work properly

### ISSUE THREAD

**Issue by flynfish** [chrismccord/sync#156]
When I don't use a scope, the sync_destroy works correctly and removes the model from the dom. 

When using a scope, the model is never removed from the dom. For some reason the update and destroy channels are different (I think they should be the same right?)

![screen shot 2014-12-15 at 10 56 48 am](https://cloud.githubusercontent.com/assets/253936/5440849/28710b2a-8449-11e4-9142-5459e0214fb2.png)

```ruby
  def destroy
    @artifact = Artifact.find params[:id]
    @artifact.update_attributes({hidden: true, verified_at: nil})

    sync_destroy @artifact
    render :json => @artifact
  end
```

```
<div class="row" id="artifacts">
  <%= sync partial: 'artifact', collection: Artifact.active_by_artifactable(@artifactable) %>
</div>
```

```ruby
sync :all
scope :shown, -> { where(hidden: false ) }
sync_scope :active_by_artifactable,   ->(artifactable) { shown.where(artifactable_id: artifactable.id) }
```

**Comment by ajb** [comment]
Perhaps fixed in https://github.com/chrismccord/sync/commit/af85616bcac551730149b43e2bd880d25427a6f3?

**Comment by ajb** [comment]
@flynfish: is this still an issue, or was it resolved in the above commit?
