### ISSUE TITLE
Specify server when using Pusher?

### ISSUE THREAD

**Issue by nadeemja** [chrismccord/sync#165]
Hi,

I'm trying to use a self-hosted Pusher service using Slanger. I set server: to localhost, but it doesn't seem to take. Is this not possible?

**Comment by ajb** [comment]
you probably need to `rake assets:clobber`. I'll add this to the README.

**Comment by nadeemja** [comment]
Thanks. But it didn't work. :(

**Comment by ajb** [comment]
So when you type `Sync.FAYE_HOST` in the console, it doesn't display the self-hosted Slanger URL? If it's not updating, then something is indeed cached.

**Comment by nadeemja** [comment]
Why would I use FAYE_HOST with Slanger?

**Comment by nadeemja** [comment]
This is what I'm doing:

development:
  adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js" 
  app_id: "61719"
  api_key: "bc2cbbeeddf28a74353e"
  auth_token: "8ae9094f52f33822285c"
  adapter: "Pusher"
  async: true
  server: 'http://localhost:8080'

**Comment by ajb** [comment]
Sorry, I got a bit confused there. Still, we're using
`adapter_javascript_url` just fine in our configuration.

On Tue, Jan 6, 2015 at 10:12 AM, Nadeem Jabbar Qureshi <
notifications@github.com> wrote:

> Why would I use FAYE_HOST with Slanger?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrismccord/sync/issues/165#issuecomment-68906119>.
>



-- 
Adam Becker
510.928.9111
@AdamJacobBecker

**Comment by ajb** [comment]
I think you need to change your adapter_javascript_url. I'm not sure why
you'd want to load pusher.min.js from js.pusher.com if you're using Slanger.

On Tue, Jan 6, 2015 at 10:14 AM, Nadeem Jabbar Qureshi <
notifications@github.com> wrote:

> This is what I'm doing:
>
> development:
> adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
> app_id: "61719"
> api_key: "bc2cbbeeddf28a74353e"
> auth_token: "8ae9094f52f33822285c"
> adapter: "Pusher"
> async: true
> server: 'http://localhost:8080'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrismccord/sync/issues/165#issuecomment-68906452>.
>



-- 
Adam Becker
510.928.9111
@AdamJacobBecker

**Comment by nadeemja** [comment]
Ok. I can't tell from the documentation which javascript url to use. I thought merely directing the calls towards the local Slanger instance would do the trick. 

Are you saying that you've successfully used Slanger?

**Comment by nadeemja** [comment]
Removing the adapter_javascript_url: parameter gives an error: Uncaught TypeError: undefined is not a function at sync.js 1:179.
