### ISSUE TITLE
Sync_scope with array.

### ISSUE THREAD

**Issue by mihailpaleologu** [chrismccord/sync#169]
Hey!
I am trying to implement a news feed using sync. The goal is to render activities belonging to users which
are followed by current user.
Here is my scope for Activity.
    sync_scope :by_user, ->(user) { where(:user_id => user.following_ids)}
user.following_ids returns an array with the ids of users that user is following.
Can you please help me? I've been stuck with on this for days yet feel like I'm getting close to a solution.
Thank you!

**Comment by ajb** [comment]
I'm not sure this is currently possible with the way your models are configured, sorry.

**Comment by mgomes** [comment]
You would need to either create a separate channel for each user's activities, which would mean that if a user follows `N` users, they would have to subscribe to `N` channels while they are viewing the news feed. (This is probably not what you want if `N` can be a large size)

The other option is to fire off a background job after an activity is created. That job would be responsible for sending a message to each user that is following the user that generated the activity.

**Comment by mihailpaleologu** [comment]
Thank you both!
Mgomes: I applied both of your solutions.
I created a separate channel for each user. But if you subscribe to more than X channels, then its handled by a background job (like on twitter, actualy).
