### ISSUE TITLE
 Uncaught ReferenceError: $el is not defined 

### ISSUE THREAD

**Issue by gauravtiwari** [chrismccord/sync#170]
Hey @chrismccord 

Can't seem to use $el in afterInsert hook. It's throwing this error 

```Javascript
afterInsert: -> 
    $el.fadeIn 'slow'
 Uncaught ReferenceError: $el is not defined
```

Thanks

**Comment by ajb** [comment]
you need to access `@$el`, with the `@`.

**Comment by gauravtiwari** [comment]
thanks @ajb (adam). Trying out coffee-script for the first time.
