### ISSUE TITLE
undefined method `[]=' for nil:NilClass

### ISSUE THREAD

**Issue by diogomonica** [chrismccord/sync#172]
While trying to create a sync_scope :by_user, ->(user) { where(user_id: user.id) }, I get this error:

```undefined method `[]=' for nil:NilClass```

looking at the code it seems that @sync_scope_definitions doesn't seem to be instantiated.

```model.rb 131: @sync_scope_definitions[name] = Sync::ScopeDefinition.new(self, name, lambda)```

**Comment by wursttheke** [comment]
Did you call `sync :all` first? 

```ruby
class Todo < ActiveRecord::Base
  belongs_to :user
  sync :all
  sync_scope :by_user, ->(user) { where(user_id: user.id) }
end
```

`@sync_scope_definitions` is instantiated here: https://github.com/chrismccord/sync/blob/master/lib/sync/model_actions.rb#L13 which is not loaded before calling `sync_scope`.
