### ISSUE TITLE
Staging Environment 

### ISSUE THREAD

**Issue by AytanLeibowitz** [chrismccord/sync#173]
I've got the gem working with Pusher in Development. I'm getting this error in my Staging Environment on Heroku: "Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4005,"message":"Path not found"}}}"

The results of typing in "Sync" in the browser console: 
CLIENT_ADAPTER: "Pusher"
FAYE_HOST: ""
PUSHER_API_KEY: ""
...

So, the PUSHER_API_KEY is not being set from the sync.yml file. I have also tried hard-coding the api_id, api_key, and auth_token, with the same results.

Here is my current sync.yml file:

development:
   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
   app_id: "<%= Pusher.app_id %>"
   api_key: "<%= Pusher.key %>"
   auth_token: "<%= Pusher.secret %>"
   adapter: "Pusher"
   async: true

staging:
   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
   app_id: "<%= Pusher.app_id %>"
   api_key: "<%= Pusher.key %>"
   auth_token: "<%= Pusher.secret %>"
   adapter: "Pusher"
   async: true

production:
   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
   app_id: "<%= Pusher.app_id %>"
   api_key: "<%= Pusher.key %>"
   auth_token: "<%= Pusher.secret %>"
   adapter: "Pusher"
   async: true

I am able to push notifications to my rails app with the staging settings. So that means I just need Sync to set the yml configs correctly. Any suggestions?

UPDATE:

I pushed the code to production and it is working properly. Is 'staging' not part of the naming convention? On Heroku I am able to reference 'staging' in other gems/configs.

**Comment by ajb** [comment]
Hi, sorry for the delay in a response. There is nothing special about how the staging environment is treated in Sync.
