### ISSUE TITLE
SyntaxError: [stdin]:7:34: unexpected )   (in c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sync-0.3.5/app/assets/javascripts/sync.coffee.erb)

### ISSUE THREAD

**Issue by himanverma** [chrismccord/sync#174]
ExecJS::RuntimeError in Sessions#index
SyntaxError: [stdin]:7:34: unexpected )
  (in c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sync-0.3.5/app/assets/javascripts/sync.coffee.erb)

**Comment by ramadhanfebbry** [comment]
I have the same problem

**Comment by ajb** [comment]
Hm, I'm having trouble understanding how this could be happening. Would you mind posting your `config/sync.yml` and `Gemfile.lock`?

**Comment by ajb** [comment]
I'm not very familiar with a Windows environment, but it sounds like you may just need to install node.js and restart? http://stackoverflow.com/questions/12520456/execjsruntimeerror-on-windows-trying-to-follow-rubytutorial

**Comment by himanverma** [comment]
Both of the files are on this link http://1drv.ms/1MnOGEZ

**Comment by ajb** [comment]
The interpolation in your YAML files is invalid, I think. Can you try
removing it and seeing if the problem persists?

On Mon, Mar 9, 2015 at 3:46 PM, Himanshu Verma <notifications@github.com>
wrote:

> Both of the files are on this link http://1drv.ms/1MnOGEZ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrismccord/sync/issues/174#issuecomment-77927603>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by himanverma** [comment]
thank issue was resolved using 
development:
   adapter: false

works for me
