### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by MichaelSp** [chrismccord/sync#177]
While I find the name "sync" really appropriate, it's rather hard to find something about it googling just for "sync". That is especially the case if you are in trouble and try to find a solutions for your "sync"-issue.

Here are some of my suggestions:
* partial-sync
* rails-sync
* rails-live

A new name containing "rails" might also bring more attention to this awesome project.

**Comment by chrismccord** [comment]
Usually pairing search with the words you described like "sync realtime rails partials" helps. I'm not up for changing the name at this point.
