### ISSUE TITLE
Synced item rendered multiple times as it is updated

### ISSUE THREAD

**Issue by pirkka** [chrismccord/sync#178]
I've been creating a very simple chat application with threaded discussions.

The object models contains Message objects in a tree, shown in a synced list. 

When a child object is created that belongs to another message (let's call it "OP"), the OP is listed twice in the view. When another reply is posted, OP is now listed three times.

I'm not familiar with the internals of sync gem, so I have no idea what is going on. 

I suspected that by using another model as a child model, I could work around this. But now that I tried saving the replies to a distinct Reply object, the same behaviour remains: whenever a Reply is created that belongs to a Message, the Message appears twice in the synced view. In this variant I'm executing "sync_update reply.message" to update the view after a new reply has been posted.

All symptoms disappear when page is reloaded, so this is not an issue in the underlying data model. Sync gem is somehow rendering duplicates of the same object in the list. Here's the list code:

          = sync_new partial: 'message', resource: Message.new, direction: :prepend 
          - @messages.each do |msg|
            = sync partial: 'message', resource: msg

Any idea on how this might be fixed? I would love keep using sync gem as opposed to finding another solution for real-time updates. :)

**Comment by chrismccord** [comment]
Have you taken a look at our caveats section? https://github.com/chrismccord/sync#current-caveats

Do you have a parent DOM node in your partial?

**Comment by pirkka** [comment]
I had taken a look at it previously, but I didn't really undestand it (I mainly looked at the code examples)... my partial looked like this:

     .message{:id => "message-#{message.id}"} 
       .body 
         = process_message_body(message.content) if message && message.content
       .replies
         = message.replies.size
       
     .reply-form{:id => "reply-form-#{message.id}"}

It must have worked fine until I added the reply-form element on the same level as the message. Adding a container element fixed this in one line:

      .message-container
        .message{:id => "message-#{message.id}"} 
          .body 
            = process_message_body(message.content) if message && message.content
          .replies
            = message.replies.size
          
        .reply-form{:id => "reply-form-#{message.id}"}

Thanks for a quick reply - problem solved!

Would it make sense to reword the documentation to say that the synced partial must only contain a single root level element? My malfunctioning code was "wrapped in a root level element" as instructed, the problem was that there were more than one root level element in the partial. Or that's how I understand it anyway :)

**Comment by chrismccord** [comment]
> Would it make sense to reword the documentation to say that the synced partial must only contain a single root level element?

Please send a PR. The wording could definitely be improved :)

**Comment by pirkka** [comment]
PR sent :)

Pirkka

**Comment by fabiosammy** [comment]
This bug not occurs in "rails 3.2", but only in >= 4.0. (With me)
