### ISSUE TITLE
Sync doesn't work on production server

### ISSUE THREAD

**Issue by flood4life** [chrismccord/sync#182]
Hello, I've got the following problem:
I use Faye configuration. Sync works properly in development and production modes on my local machine, but it doesn't work on production server. Though Faye on production server is up and running.
I run Faye with `bundle exec thin -p 9292 -e production -R sync.ru start`

**Comment by Epigene** [comment]
I, too, am having trouble getting Sync to work on staging (and production) server.

My stack is:
  + Rails app accessible at https://staging.domain.com
  + Nginx reverse proxy enforcing SSL
  + init.d script running Sync on boot via `bundle exec rackup sync.ru -E production`

Frankly, I am confused by the `-E production` requirement even in development and am not sure what configuration (if any) is loaded from `config/sync.yml` and what it should look like for production environment using my stack.

**Comment by MichaelSp** [comment]
same here: local OK, remote Not working.

Same stack as @Epigene but without enforcing SSL
Here is my `Procfile`

```
web:      bundle exec unicorn -c ./config/unicorn.rb
worker:   bundle exec sidekiq -c 5 -e production
sync:     bundle exec rackup sync.ru -E production -p 9292
redis:    redis-server --maxclients 3984
```

And I'm also confused by the different environments and why to run what?!

What I discovered so far:
 * Websocket connection seems to be OKish
 * Sync events are pushed to the browser
 * Website doesn't change
 * no error in js-console

**Comment by MichaelSp** [comment]
I found my mistake in `config/sync.yml`.

Change this
```
production:
   server: "/faye"
```
to this
```
production:
   server: "http://localhost:9292/faye"
```

**Comment by ajb** [comment]
I'm opening #194 in order to improve the quality of our documentation.

**Comment by grepruby** [comment]
Have struggled a bit to get it work on staging/production. 
You need to start the server with below command

    RAILS_ENV=production bundle exec rackup sync.ru -E production
