### ISSUE TITLE
Possibility to keep current_user

### ISSUE THREAD

**Issue by owolanger** [chrismccord/sync#183]
Idk where i can ask my questions, so i try here.
I'm working on a little app where the admin can block/unblock different user areas.

I used sync like:
```
<%= sync partial: 'user_area', resource: @area %>
```
The syncing works fine.
My problem now is that i use something like:
```
<% if !current_user.admin? %>
```
or 
```
<%= current_user.name %>
```
in my _user_area.html.erb

After unblock the area the wrong current_user is shown (current_user is now the guy who unblocked the area and not the current user). After refreshing the right content is shown.

**Comment by mgomes** [comment]
Check out https://github.com/chrismccord/sync#refetching-partials. The partial is rendered in the context of the user making the request (the guy who unblocked the area). So if the partial depends on something specific for the `current_user` it won't work unless each user refetches.
