### ISSUE TITLE
Differentiate between machines?

### ISSUE THREAD

**Issue by swaathi** [chrismccord/sync#184]
This is a weird thing that I'm experiencing, when I update something on my dev machine, it comes up on my production server. I have scoped to it's parent resource, something like this,

`<%= sync_new :partial => 'showtr', resource: Myfile.new, scope: myfolder %>`

Is there anything that I can do to avoid this? I have some authentication keys that are different for each machine, I was hoping I could make use of that somehow to let Sync know not to confuse machines?

**Comment by chrismccord** [comment]
It sounds like you have the same credentials in your `sync.yml` for both dev and prod?

**Comment by swaathi** [comment]
Yup that's true! I'm using Pusher. I don't think I can generate different keys in Pusher for different devices?

**Comment by ajb** [comment]
Yes, you can. I have a separate application in Pusher called "Myapp [Dev]" for just this reason.

Best,
Adam
