### ISSUE TITLE
Having trouble with sync in production on Heroku

### ISSUE THREAD

**Issue by tsbernar** [chrismccord/sync#185]
Using pusher snyc works perfectly fine in development, but in production (using heroku) I don't get real time updates.  Pusher is seeing the messages, but it seems like the browser is not recieving the messages back from pusher.

**Comment by tsbernar** [comment]
Fixed this issue, i was getting an error in production 'http://js.pusher.com/2.0/pusher.min.js' being blocked.  I changed this in the config/sync.yml file to 'https://js.pusher.com/2.0/pusher.min.js' and it now works.

**Comment by chrismccord** [comment]
Glad you got things sorted out
