### ISSUE TITLE
Uncaught exception: undefined method `sync' for #<Class:0x007fb7910530c0>

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [chrismccord/sync#187]
I began getting this error when I included "sync :all" into some of my ActiveRecord classes that use sync. For some of the classes that do not use class_eval string interpolation, it works. However, for others it throws the exception. I elaborate on the issue on this stackoverflow post:

http://stackoverflow.com/questions/30132590/class-eval-block-argument-and-class-eval-string-argument-differences

**Comment by MichaelSp** [comment]
I think this can be closed, as the SO post contains an accepted answer
