### ISSUE TITLE
[Question] Require Sync for Single Page

### ISSUE THREAD

**Issue by trigun0x2** [chrismccord/sync#189]
Currently, does Sync automatically open a connection to Pusher for every user on any site or only the pages where a sync partial exists?

If the first case is true, is it possible to require sync/pusher only on certain pages?

Thanks!

**Comment by ajb** [comment]
Hi @trigun0x2:

Sync will open a new connection on any page where the following code is included:

```erb
<%= javascript_include_tag Sync.adapter_javascript_url %>
```

Just leave that out of your page and you should be golden.
