### ISSUE TITLE
How to trigger sync without updating record?

### ISSUE THREAD

**Issue by juanpastas** [chrismccord/sync#193]
Hi,

I am currently doing `record.update updated_at: Time.now` to trigger that record sync actions.

I have been reading the code, but is not clear for me what method I should use to trigger sync without updating record. Is that possible?

The idea behind it is to save some DB load and do not pollute updated_at purpose. If that makes any sense.

**Comment by ajb** [comment]
`sync_update(record)` doesn't care if your record has actually been updated or not.

**Comment by juanpastas** [comment]
how do I use it? I tried `Teacher.sync_update(record)`.

**Comment by ajb** [comment]
If you `include Sync::Actions` in a class, it will have access to the
`sync_update` class method.

On Wed, Jul 1, 2015 at 10:55 AM, Juan David Pastas <notifications@github.com
> wrote:

> how do I use it? I tried Teacher.sync_update(record).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrismccord/sync/issues/193#issuecomment-117706908>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by juanpastas** [comment]
I used `extend` instead of `include`, I will make a complete test.
