### ISSUE TITLE
Documentation on environment-specific configuration could be clearer

### ISSUE THREAD

**Issue by ajb** [chrismccord/sync#194]
cf #182, #185, #133, etc...

**Comment by Epigene** [comment]
I could use documentation for setting up sync on what I understand is a pretty popular and basic rails app production configuration - nginx reverse-proxy + https, thanks.

**Comment by ajb** [comment]
Are you using Pusher or Faye?

**Comment by Epigene** [comment]
Faye.

**Comment by ajb** [comment]
This should be closed by https://github.com/chrismccord/sync/pull/204. Note that `0.4.0` is not yet pushed to rubygems, so you'll have to install from GitHub.
