### ISSUE TITLE
Javascript hooks and refetch not working.

### ISSUE THREAD

**Issue by MindRave** [chrismccord/sync#197]
Hi everyone.

First of all, thanks for the great gem! :+1: 

I am implementing sync with the Mailboxer gem (on Faye), in order to make user messages realtime. The basic functionality works. Message sent - message received, no problem.

Here is my setup:

**ConversationsController**
```ruby
def reply
  @reply = current_user.reply_to_conversation(@conversation, params[:body])
  sync_new @reply, scope: @conversation
end
```

**show.html.erb**
```erb
<div class="messages">
  <% @conversation.receipts_for(current_user).each do |receipt| %>
    <%= sync partial: 'receipt', resource: receipt %>
  <% end %>
  <%= sync_new partial: 'receipt', resource: current_user.reply_to_conversation(@conversation, params[:body]), scope: @conversation %>
</div>
```

The partial is named "receipt", and it's placed in "sync/mailboxer/receipts" because otherwise (if I place it just in "sync/receipts"), I get a "partial not found" error.

As I said, the above works just fine for the basic functionality.

**Issue No1**
Refetch: true won't work. Simply adding refetch:true results in a **400 - "Bad request"** from the server. The "_receipt.html.erb" partial is located in "sync/mailboxer/receipts/refetch".

**Issue No2**
JavaScript hooks. I want to do a few things after loading the message, such as scrolling the container up a bit to show the message, but the hooks do not respond. Here is the application.coffee, with a simple alert for the afterUpdate:
```coffeescript
class Sync.Receipt extends Sync.View
  afterUpdate: -> alert "Hello!"
```
I tried changing "Receipt" to "MailboxerReceipt", but got nothing. I suspect this is happening because of the folder structure ("sync/mailboxer/receipts" instead of just "sync/receipts"), but correct me if I'm wrong.

Thanks again, and any help would be really appreciated!

**Comment by jrpolidario** [comment]
Also having the same problem. Although beforeInsert and afterInsert are invoked properly (I can see my log outputs generated in the console). However, beforeUpdate, afterUpdate, beforeRemove, and afterRemove doesn't seem to get called (although I can see the page updates/removes partials properly, but the callbacks doesn't just get called)

**Comment by jrpolidario** [comment]
I managed to work it now! :sweat_smile: Found out that my
```coffeescript
$(->
  class Sync.CustomerIndexDiv extends Sync.View

      beforeInsert: ($el) ->
        $el.hide()
        @insert($el)
    # ...
    # ...
)
```
has the `$(->)` on it which translates Jquery's ready() function, as I put it there initially as I thought that the page needs to be loaded first before this javascript is invoked. But it looks like, conversely it creates the problem for me :smile: After removing the `$(->)` wrapper, beforeUpdate, afterUpdate, beforeRemove, and afterRemove are now being invoked properly. You can try checking your code if you have a $(document.ready(function() {}) or the above Jquery $(function(){}), and try removing them for these extendes View classes. Hopefully that will solve you problem too :smiley:

**Comment by MindRave** [comment]
@jrpolidario Thank you so much for your help! Seems to work now. At least for the beforeInsert and afterInsert. :smile: 

P.S: refetch: true still doesn't work, however. If anyone has any ideas on what could be messing it up, that would be awesome of you! It'd be great to be able to sync partials in the context they're served (e.g such as partials belonging to "current_user" ).

Thank you again!

**Comment by jrpolidario** [comment]
It's my pleasure! :)
I just started using `refetch: true` now (I am not using mailboxer). It's working for me. I can verify this because in my partial sync file, I have `<%= current_user.first_name %>` which returns properly the name of the current user who's browsing  the page where the partial  file gets  rendered. I tried adding turbolinks (just in case if you're using it), but it still works for me. Maybe this is already mailboxer incompatibility. Best of luck! :)

**Comment by WilliamLINWEN** [comment]
Issue No1
@MindRave 
I also have the same problem. Server log shows
```
Filter chain halted as :find_resource rendered or redirected
Completed 400 Bad Request in 28ms 
```

It seem there is problem with `refetchs_controllers#find_resource`
 ```ruby
  def find_resource
    @resource = RenderSync::RefetchModel.find_by_class_name_and_id(
      params[:resource_name],
      params[:resource_id]
    ) || render_bad_request
  end
```
` RenderSync::RefetchModel.find_by_class_name_and_id` call the method `RefetchModel#self.supported_classes` to check something.
However, in the `supported_classes` , `Dir["app/views/sync/*/refetch"]` return empty array. 
The correct path should contain `app/view/sync/mailboxer/receipts/refetch`. 
I think  `refetech:true` may not work on model with namespace. Sorry for my poor English.
