### ISSUE TITLE
FIX: Documentation should be clearer that it requires turbolinks to work when viewed remotely

### ISSUE THREAD

**Issue by jrpolidario** [chrismccord/sync#200]
Been stuck for a while now, but finally figured out that turbolinks is required to work remotely. When viewing the page locally, it works fine, i.e. new posts on my page appear when new posts created. However, when it is going to be viewed by remote machines: i.e. my Iphone: new posts doesn't doesn't appear.

I removed turbolinks way back before, but after adding it back by trial and error, it works. I do not know the specifics why. But if this is really required, I hope you could update the documentation so that future readers having the same issues will be helped.

Thanks.

**Comment by ajb** [comment]
Hm, Turbolinks should not be required in order for Sync to work.

**Comment by jrpolidario** [comment]
Oh I see... If I get the time I'll try to check on this. I guess then it was in my actual javascript code that caused the problem I had.
