### ISSUE TITLE
Full API reference

### ISSUE THREAD

**Issue by DannyBen** [chrismccord/sync#205]
Is there a more-than-readme API reference other than the auto generated documentation?

I am finding myself collecting bits and pieces of solutions from the README, which is good, but I am looking for a more structured API reference.

Some questions I am facing for example:

1. Can I pass parameters to a synced partial
2. I had a problem where my partial included current_user reference, which broke (found the fix in one of the issues)
3. Do I have to also add `<%= sync_new partial: ... %>`? What are its options?
4. Can I sync a collection instead of a member? I wish to maintain the same order of members.
5. What are all the available `sync_*` methods

If there is no such documentation, I would like to suggest making one (doesnt have to be long or complex) in the github wiki or maybe even github pages. If not that, then at least a wiki page with direct links to relevant places in the rdocs, like [Controller Sync Methods](http://www.rubydoc.info/gems/sync/0.3.5/Sync/Actions)

**Comment by ajb** [comment]
I'd agree that the README / documentation could use an update. Unfortunately, the original maintainer is now busy with other (awesome) projects, and I've not got much time to assist with non-urgent projects like docs. Also, I apologize for the long delay in answering your question!

> Can I pass parameters to a synced partial

Nope, the synced partial only has knowledge of its `resource`. (the model)

> I had a problem where my partial included current_user reference, which broke (found the fix in one of the issues)

Yup, you can use `refetch` if you need the `current_user`.

> Can I sync a collection instead of a member?

If your collection `belongs_to` another resource, than yes. Imagine you have a user that `has_many` comments, and you want to display the list of comments. You can do `sync partial: 'comments', resource: @user`, and when you update the `@user`, it will update the list. 

I'd be more than happy to review PRs to the documentation, if this is a project that you'd be willing to take on. 

I hope the library is working well for you!
