### ISSUE TITLE
Query optimization for multiple segmentation

### ISSUE THREAD

**Issue by devilankur18** [chrismccord/sync#206]
I am using sync for a usecase of tickets who have different statuses tracked by enum value

    class Ticket
      enum status: { initiated: 0, active: 1, closed: 2 , review_pending: 3, completed: 4, rejected: 5, trash: 6}

      sync :all 

      statuses.each do |key, value|
        sync_scope "recent_#{key}",->() { send(key) }
      end

      after_create :update_started_at
      after_commit :last_activity_at
      after_commit :update_metadata

      def update_started_at
        self.update_attributes(:geneted_at, Time.now)
      end

      def last_activity_at
        self.update_attributes(:geneted_at, Time.now)
      end

      def update_metadata
        # Do a save operation
      end

    end

          

To keep track of updates on any of the above status, multiple sync_scope need to be created. Problems

- On create/update/destroy all the sync scopes been evaluated which execute extra 7 queries, which seems an overkill. Is there some way to optimise it using group_by or related queries

- Secondly, if there are callbacks which make any further save, the scope evaluation is triggered again. It seems after_commit scope evaluation event queue dont have unique events. Overall it increase the scope evaluation queries multiple folds.

- Is it possible to do a sync :all  with a condition ?

Please help me out here

**Comment by ajb** [comment]
Hi,

It sounds like it might be better to remove `sync :all` and trigger the calls to `sync_update`/`sync_new`/`sync_destroy` manually. Here's why:

> On create/update/destroy all the sync scopes been evaluated which execute extra 7 queries, which seems an overkill. Is there some way to optimise it using group_by or related queries

I don't think so...

> Secondly, if there are callbacks which make any further save, the scope evaluation is triggered again. 

There's no way for Sync to know that those callbacks exist. (Also, multiple saves in the same HTTP request sounds like it should be optimized, too?) If you trigger the events manually, you can simply skip the first call to `sync_update`.

> Is it possible to do a sync :all with a condition ?

Nope, but you can certainly implement this yourself. `sync :all` is pretty simple -- it just sets up the callbacks for you: https://github.com/chrismccord/sync/blob/2bc0a02af0a3bbc08132f55802981ce773fab72f/lib/sync/model.rb#L48-L58
