### ISSUE TITLE
faye is not working on aws, even there is not any error in browser console

### ISSUE THREAD

**Issue by mahhek** [chrismccord/sync#209]
Hey Following are the details,

rails c production
2.2.0 :002 > Sync.server
=> "http://54.174.159.154:9292/faye" 

http://54.174.159.154:9292/faye/faye.js

but problem I am finding is that my partials are not refreshing, its not working on aws production but working on local system.

this it the command I used.

rackup sync.ru -o 0.0.0.0 -E production
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:9292, CTRL+C to stop

Also this is my sync.yml file

production:
  server: "http://54.174.159.154:9292/faye"
  adapter_javascript_url: "http://54.174.159.154:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "somerandomtoken"
  async: true

Please help me asap, thanks.

**Comment by devilankur18** [comment]
Suggestions / Questions
- Is you aws server behind Load balancer ? if yes, is loadbalancer configured for websocket ?
- See any errors related to websocket in the browser javascript console
- Make sure that sync javascript, which has been generated have the right production url, if not clear and force regenerate assets

**Comment by mahhek** [comment]
Hey @devilankur18  thanks fore your reply, appreciated.
It is not behind LoadBalancer.
About js is rendering or not, see this link http://54.174.159.154:9292/faye/faye.js, js is opening, it means it is rendering well, so nay other idea?

**Comment by devilankur18** [comment]
@mahhek I was mentioning FAYE_HOST variable inside sync.js file, which should merged be application.js file in production after asset pipeline compression. See whats the value of the variable, that will decide which host is your sync connecting to, you local or production host.

**Comment by mahhek** [comment]
so you are saying that I should create sync.js then I should mention
FAYE_HOST: "Faye"
and then precompile it by mentioning //require sync.js in application.js?

**Comment by devilankur18** [comment]
@mahhek No I am not saying that. As part of sync gem setup, a file need to included in the application.js. That file has a host variable which is evaluated during asset precompile using the settings in sync.yml. I have faced once issue in the past, that variable was using the old value, so I need to clear assets and again recompile them. 
```
//= require sync
```

I have checked the sync.js related code on you webpage, seems the problem I am mentioning is not there. Its something else.

**Comment by mahhek** [comment]
Hey, thanks again for your reply.

I included it and precompiled as well.
you can see

now in my application.js(compiled version) and 

value looks like set

FAYE_HOST:"http://54.174.159.154:9292/faye",PUSHER_API_KEY:"",CLIENT_ADAPTER:"Faye"

what could else be the reason?

**Comment by ajb** [comment]
Closing this, as it looks like a configuration issue.

FWIW, it looks like your server isn't accessible to the public on port 9292. (Accessing http://54.174.159.154:9292/ gives an `ERR_CONNECTION_REFUSED`.)

**Comment by mahhek** [comment]
Hey, I was playing with the server, don't mark it close, If you want to see you can check it now. thanks.

**Comment by grepruby** [comment]
In case if someone still have this issue, please use below to start the faye server below

RAILS_ENV=staging bundle exec rackup sync.ru -E production
