### ISSUE TITLE
callback method or something which tell that all browsers/clients are updated

### ISSUE THREAD

**Issue by mahhek** [chrismccord/sync#210]
I have a scenario like I update multiple browsers via sync, it take different amount of seconds to update all the clients depending upon the number of browsers, I need a method or something which tell me that for particular request all the clients/browsers are updated. So that I can enable some buttons which I need to enable at the end of all browsers updation .

**Comment by ajb** [comment]
Hi,

It sounds like you need full-duplex communications. Websockets can support this, but it's not the goal of sync to provide this functionality.
