### ISSUE TITLE
script tags and `:first-child` / `:last-child`

### ISSUE THREAD

**Issue by aaronjensen** [chrismccord/sync#38]
It seems that the script tags that are rendered take the place of first-child or last-child when you're trying to do css styling. I'm not sure what to do about this other than manually add classes to the first/last :/

**Comment by jakewtaylor** [comment]
If anyone else ends up here from Google trying to find out how to ignore 'script' tags when using `:last-child`, I found a solution that seems to work for me:
```CSS
.parent > *:not(script):last-of-type {
    /* voila! */
}
```
